version: '3.7'
services:
  redis:
    image: 'redis:alpine'
    networks:
      - net
  minio:
    image: 'minio/minio'
    hostname: minio
    environment:
      MINIO_ACCESS_KEY: '${MINIO_ACCESS_KEY?Variable MINIO_ACCESS_KEY not set}'
      MINIO_SECRET_KEY: '${MINIO_SECRET_KEY?Variable MINIO_SECRET_KEY not set}'
    volumes:
      - minio-data:/data
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    deploy:
      labels:
        traefik.enable: 'true'
        traefik.docker.network: traefik-public
        traefik.constraint-label: traefik-public
        traefik.http.routers.sissgo-minio-http.rule: 'Host(`minio.${VIRTUAL_HOST?Variable VIRTUAL_HOST not set}`)'
        traefik.http.routers.sissgo-minio-http.entrypoints: http
        traefik.http.routers.sissgo-minio-http.middlewares: https-redirect
        traefik.http.routers.sissgo-minio-https.rule: 'Host(`minio.${VIRTUAL_HOST?Variable VIRTUAL_HOST not set}`)'
        traefik.http.routers.sissgo-minio-https.entrypoints: https
        traefik.http.routers.sissgo-minio-https.tls: 'true'
        traefik.http.routers.sissgo-minio-https.tls.certresolver: le
        traefik.http.services.sissgo-minio.loadbalancer.server.port: '9000'
    networks:
      - net
      - traefik-public
  db:
    image: 'postgres:13-alpine'
    volumes:
      - 'db_data:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: '${POSTGRES_USER?Variable POSTGRES_USER not set}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD?Variable POSTGRES_PASSWORD not set}'
    ports:
      - '${POSTGRES_PORT?Variable POSTGRES_PORT not set}:5432'
    networks:
      - net
  front:
    image: '$CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_SHA'
    build:
      context: ./../frontend
    command: >-
      bash -c "cd /app && npm config set scripts-prepend-node-path true && yarn
      install && yarn build && yarn start:prod"
    environment:
      VIRTUAL_HOST: https://api.${VIRTUAL_HOST?Variable VIRTUAL_HOST not set}
      CLIENT_ID: ${CLIENT_ID?Variable APP_KEY not set}
      CLIENT_SECRET: ${CLIENT_SECRET?Variable APP_KEY not set}
    deploy:
      labels:
        traefik.enable: 'true'
        traefik.docker.network: traefik-public
        traefik.constraint-label: traefik-public
        traefik.http.routers.sissgo-http.rule: 'Host(`${VIRTUAL_HOST?Variable VIRTUAL_HOST not set}`)'
        traefik.http.routers.sissgo-http.entrypoints: http
        traefik.http.routers.sissgo-http.middlewares: https-redirect
        traefik.http.routers.sissgo-https.rule: 'Host(`${VIRTUAL_HOST?Variable VIRTUAL_HOST not set}`)'
        traefik.http.routers.sissgo-https.entrypoints: https
        traefik.http.routers.sissgo-https.tls: 'true'
        traefik.http.routers.sissgo-https.tls.certresolver: le
        traefik.http.services.sissgo.loadbalancer.server.port: '3000'
    networks:
      - net
      - traefik-public
    depends_on:
      - backend
  backend:
    image: '$CI_REGISTRY_IMAGE/backend:$CI_COMMIT_SHA'
    build:
      context: ./../backend
    command: >-
      bash -c "cd /var/www && composer install && cp .env.example .env && php artisan config:cache &&  php artisan passport:key --force && php artisan migrate --force && chown -hR $user:www-data /var/www && chmod -R 775 /var/www/ && php artisan storage:link && php artisan passport:key && php artisan l5-swagger:generate && apachectl -D FOREGROUND"
    environment:
      APP_NAME: SisSGO
      APP_KEY: ${APP_KEY?Variable APP_KEY not set}
      APP_ENV: production
      APP_DEBUG: 'false'
      APP_URL: 'https://api.${VIRTUAL_HOST?Variable VIRTUAL_HOST not set}'
      L5_SWAGGER_CONST_HOST: 'https://api.${VIRTUAL_HOST?Variable VIRTUAL_HOST not set}'
      ENABLE_HTTPS: 'true'
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: '${POSTGRES_USER?Variable POSTGRES_USER not set}'
      DB_USERNAME: '${POSTGRES_USER?Variable POSTGRES_USER not set}'
      DB_PASSWORD: '${POSTGRES_PASSWORD?Variable POSTGRES_PASSWORD not set}'
      MINIO_ENDPOINT: 'http://minio.${VIRTUAL_HOST?Variable VIRTUAL_HOST not set}'
      MINIO_KEY: '${MINIO_ACCESS_KEY?Variable MINIO_ACCESS_KEY not set}'
      MINIO_SECRET: '${MINIO_SECRET_KEY?Variable MINIO_SECRET_KEY not set}'
      MINIO_BUCKET: 'sissgo'
    deploy:
      labels:
        traefik.enable: 'true'
        traefik.docker.network: traefik-public
        traefik.constraint-label: traefik-public
        traefik.http.routers.sissgo-api-http.rule: 'Host(`api.${VIRTUAL_HOST?Variable VIRTUAL_HOST not set}`)'
        traefik.http.routers.sissgo-api-http.entrypoints: http
        traefik.http.routers.sissgo-api-http.middlewares: https-redirect
        traefik.http.routers.sissgo-api-https.rule: 'Host(`api.${VIRTUAL_HOST?Variable VIRTUAL_HOST not set}`)'
        traefik.http.routers.sissgo-api-https.entrypoints: https
        traefik.http.routers.sissgo-api-https.tls: 'true'
        traefik.http.routers.sissgo-api-https.tls.certresolver: le
        traefik.http.services.sissgo-api.loadbalancer.server.port: '80'
    networks:
      - net
      - traefik-public
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/v1"]
      interval: 30s
      timeout: 20s
      retries: 10
    depends_on:
      - db
networks:
  net:
    driver: overlay
    attachable: true
  traefik-public:
    external: true
volumes:
  db_data: {}
  minio-data: {}
