version: "3.7"
services:

    mailhog:
      image: mailhog/mailhog:latest
      networks:
        - net
      ports:
        - "5098:8025"

    redis:
      image: redis:alpine
      networks:
        - net

    db:
      image: postgres:13-alpine
      environment:
        - POSTGRES_USER=${POSTGRES_USER?Variable POSTGRES_USER not set}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable POSTGRES_PASSWORD not set}
      ports:
        - ${POSTGRES_PORT?Variable POSTGRES_PORT not set}:5432
      networks:
        - net

    front:
      image: node:latest
      working_dir: /app
      volumes:
        - ${CODE_PATH}_dev/frontend/:/app
      # ports:
      #   - ${FRONTEND_PORT?Variable FRONTEND_PORT not set}:3000
      command: bash -c "npm config set scripts-prepend-node-path true && yarn install && yarn build && yarn start"
      deploy:
        labels:
          traefik.tags: traefik-public
          traefik.redirectorservice.frontend.redirect.entryPoint: https
          traefik.webservice.frontend.entryPoints: https
          traefik.redirectorservice.frontend.entryPoints: http
          traefik.docker.network: traefik-public
          traefik.enable: 'true'
          traefik.port: '3000'
          traefik.frontend.rule: Host:${VIRTUAL_HOST?Variable VIRTUAL_HOST not set}
      networks:
        - net
        - traefik-public
      depends_on:
        - backend

    webserver:
      image: nginx:alpine
      working_dir: /application
      volumes:
        - ${CODE_PATH}_dev/backend/:/application
        - ${CODE_PATH}_dev/dockerfiles/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      deploy:
        labels:
          traefik.tags: traefik-public
          traefik.redirectorservice.frontend.redirect.entryPoint: https
          traefik.webservice.frontend.entryPoints: https
          traefik.redirectorservice.frontend.entryPoints: http
          traefik.docker.network: traefik-public
          traefik.enable: 'true'
          traefik.port: '80'
          traefik.frontend.rule: Host:api.${VIRTUAL_HOST?Variable VIRTUAL_HOST not set}
      networks:
        - net
        - traefik-public
      depends_on:
        - php-fpm

    php-fpm:
      image: luizjrdeveloper/php74-fpm-laravel:latest
      working_dir: /application
      volumes:
        - ${CODE_PATH}_dev/backend/:/application
      networks:
        - net
      depends_on:
        - db

networks:
  net:
    driver: overlay
    attachable: true
  traefik-public:
    external: true

volumes:
  db_data: {}
