//= ====================================
//  CRUD
//-------------------------------------

export const CREATE_ATIVIDADE = 'CREATE_ATIVIDADE';
export const INIT_CREATE_ATIVIDADE = 'INIT_CREATE_ATIVIDADE';
export const CREATE_ATIVIDADE_SUCCESS = 'CREATE_ATIVIDADE_SUCCESS';
export const CREATE_ATIVIDADE_FAILURE = 'CREATE_ATIVIDADE_FAILURE';

export const UPDATE_ATIVIDADE = 'UPDATE_ATIVIDADE';
export const INIT_UPDATE_ATIVIDADE = 'INIT_UPDATE_ATIVIDADE';
export const UPDATE_ATIVIDADE_SUCCESS = 'UPDATE_ATIVIDADE_SUCCESS';
export const UPDATE_ATIVIDADE_FAILURE = 'UPDATE_ATIVIDADE_FAILURE';

export const REMOVE_ATIVIDADE = 'REMOVE_ATIVIDADE';
export const REMOVE_ATIVIDADE_SUCCESS = 'REMOVE_ATIVIDADE_SUCCESS';
export const REMOVE_ATIVIDADE_FAILURE = 'REMOVE_ATIVIDADE_FAILURE';

export const SET_ATIVIDADES = 'SET_ATIVIDADES';
export const SET_ATIVIDADE = 'SET_ATIVIDADE';
export const LIST_ATIVIDADES = 'LIST_ATIVIDADES';
export const PAGINATE_ATIVIDADES = 'PAGINATE_ATIVIDADES';

export const FETCH_ATIVIDADE = 'FETCH_ATIVIDADE';
export const FETCH_ATIVIDADE_FAILED = 'FETCH_ATIVIDADE_FAILED';
export const FETCH_ATIVIDADE_SUCCESS = 'FETCH_ATIVIDADE_SUCCESS';
