//= ====================================
//  CRUD
//-------------------------------------

export const CREATE_CERTIFICADO = 'CREATE_CERTIFICADO';
export const CREATE_CERTIFICADO_MODAL = 'CREATE_CERTIFICADO_MODAL';
export const INIT_CREATE_CERTIFICADO = 'INIT_CREATE_CERTIFICADO';
export const CREATE_CERTIFICADO_SUCCESS = 'CREATE_CERTIFICADO_SUCCESS';
export const CREATE_CERTIFICADO_FAILURE = 'CREATE_CERTIFICADO_FAILURE';

export const UPDATE_CERTIFICADO = 'UPDATE_CERTIFICADO';
export const INIT_UPDATE_CERTIFICADO = 'INIT_UPDATE_CERTIFICADO';
export const UPDATE_CERTIFICADO_SUCCESS = 'UPDATE_CERTIFICADO_SUCCESS';
export const UPDATE_CERTIFICADO_FAILURE = 'UPDATE_CERTIFICADO_FAILURE';

export const REMOVE_CERTIFICADO = 'REMOVE_CERTIFICADO';
export const REMOVE_CERTIFICADO_SUCCESS = 'REMOVE_CERTIFICADO_SUCCESS';
export const REMOVE_CERTIFICADO_FAILURE = 'REMOVE_CERTIFICADO_FAILURE';

export const SET_CERTIFICADOS = 'SET_CERTIFICADOS';
export const SET_CERTIFICADO = 'SET_CERTIFICADO';
export const SET_CERTIFICADO_SITUACOES = 'SET_CERTIFICADO_SITUACOES';
export const LIST_CERTIFICADOS = 'LIST_CERTIFICADOS';
export const PAGINATE_CERTIFICADOS = 'PAGINATE_CERTIFICADOS';
export const LIST_CERTIFICADO_SITUACOES = 'LIST_CERTIFICADO_SITUACOES';

export const FETCH_CERTIFICADO = 'FETCH_CERTIFICADO';
export const FETCH_CERTIFICADO_FAILED = 'FETCH_CERTIFICADO_FAILED';
export const FETCH_CERTIFICADO_SUCCESS = 'FETCH_CERTIFICADO_SUCCESS';
