//= ====================================
//  CRUD
//-------------------------------------

export const CREATE_CLIENTE = 'CREATE_CLIENTE';
export const INIT_CREATE_CLIENTE = 'INIT_CREATE_CLIENTE';
export const CREATE_CLIENTE_SUCCESS = 'CREATE_CLIENTE_SUCCESS';
export const CREATE_CLIENTE_FAILURE = 'CREATE_CLIENTE_FAILURE';

export const UPDATE_CLIENTE = 'UPDATE_CLIENTE';
export const INIT_UPDATE_CLIENTE = 'INIT_UPDATE_CLIENTE';
export const UPDATE_CLIENTE_SUCCESS = 'UPDATE_CLIENTE_SUCCESS';
export const UPDATE_CLIENTE_FAILURE = 'UPDATE_CLIENTE_FAILURE';

export const REMOVE_CLIENTE = 'REMOVE_CLIENTE';
export const REMOVE_CLIENTE_SUCCESS = 'REMOVE_CLIENTE_SUCCESS';
export const REMOVE_CLIENTE_FAILURE = 'REMOVE_CLIENTE_FAILURE';

export const SET_CLIENTES = 'SET_CLIENTES';
export const SET_CLIENTE = 'SET_CLIENTE';
export const LIST_CLIENTES = 'LIST_CLIENTES';
export const PAGINATE_CLIENTES = 'PAGINATE_CLIENTES';

export const FETCH_CLIENTE = 'FETCH_CLIENTE';
export const FETCH_CLIENTE_FAILED = 'FETCH_CLIENTE_FAILED';
export const FETCH_CLIENTE_SUCCESS = 'FETCH_CLIENTE_SUCCESS';
