//= ====================================
//  CRUD
//-------------------------------------

export const CREATE_EQUIPAMENTO = 'CREATE_EQUIPAMENTO';
export const INIT_CREATE_EQUIPAMENTO = 'INIT_CREATE_EQUIPAMENTO';
export const CREATE_EQUIPAMENTO_SUCCESS = 'CREATE_EQUIPAMENTO_SUCCESS';
export const CREATE_EQUIPAMENTO_FAILURE = 'CREATE_EQUIPAMENTO_FAILURE';

export const UPDATE_EQUIPAMENTO = 'UPDATE_EQUIPAMENTO';
export const INIT_UPDATE_EQUIPAMENTO = 'INIT_UPDATE_EQUIPAMENTO';
export const UPDATE_EQUIPAMENTO_SUCCESS = 'UPDATE_EQUIPAMENTO_SUCCESS';
export const UPDATE_EQUIPAMENTO_FAILURE = 'UPDATE_EQUIPAMENTO_FAILURE';

export const REMOVE_EQUIPAMENTO = 'REMOVE_EQUIPAMENTO';
export const REMOVE_EQUIPAMENTO_SUCCESS = 'REMOVE_EQUIPAMENTO_SUCCESS';
export const REMOVE_EQUIPAMENTO_FAILURE = 'REMOVE_EQUIPAMENTO_FAILURE';

export const SET_EQUIPAMENTOS = 'SET_EQUIPAMENTOS';
export const SET_EQUIPAMENTO = 'SET_EQUIPAMENTO';
export const LIST_EQUIPAMENTOS = 'LIST_EQUIPAMENTOS';
export const PAGINATE_EQUIPAMENTOS = 'PAGINATE_EQUIPAMENTOS';

export const FETCH_EQUIPAMENTO = 'FETCH_EQUIPAMENTO';
export const FETCH_EQUIPAMENTO_FAILED = 'FETCH_EQUIPAMENTO_FAILED';
export const FETCH_EQUIPAMENTO_SUCCESS = 'FETCH_EQUIPAMENTO_SUCCESS';
