//= ====================================
//  CRUD
//-------------------------------------

export const CREATE_EXAME = 'CREATE_EXAME';
export const CREATE_EXAME_MODAL = 'CREATE_EXAME_MODAL';
export const INIT_CREATE_EXAME = 'INIT_CREATE_EXAME';
export const CREATE_EXAME_SUCCESS = 'CREATE_EXAME_SUCCESS';
export const CREATE_EXAME_FAILURE = 'CREATE_EXAME_FAILURE';

export const UPDATE_EXAME = 'UPDATE_EXAME';
export const INIT_UPDATE_EXAME = 'INIT_UPDATE_EXAME';
export const UPDATE_EXAME_SUCCESS = 'UPDATE_EXAME_SUCCESS';
export const UPDATE_EXAME_FAILURE = 'UPDATE_EXAME_FAILURE';

export const REMOVE_EXAME = 'REMOVE_EXAME';
export const REMOVE_EXAME_SUCCESS = 'REMOVE_EXAME_SUCCESS';
export const REMOVE_EXAME_FAILURE = 'REMOVE_EXAME_FAILURE';

export const SET_EXAMES = 'SET_EXAMES';
export const SET_EXAME = 'SET_EXAME';
export const LIST_EXAMES = 'LIST_EXAMES';
export const PAGINATE_EXAMES = 'PAGINATE_EXAMES';

export const FETCH_EXAME = 'FETCH_EXAME';
export const FETCH_EXAME_FAILED = 'FETCH_EXAME_FAILED';
export const FETCH_EXAME_SUCCESS = 'FETCH_EXAME_SUCCESS';
