//= ====================================
//  CRUD
//-------------------------------------

export const CREATE_FUNCIONARIO = 'CREATE_FUNCIONARIO';
export const INIT_CREATE_FUNCIONARIO = 'INIT_CREATE_FUNCIONARIO';
export const CREATE_FUNCIONARIO_SUCCESS = 'CREATE_FUNCIONARIO_SUCCESS';
export const CREATE_FUNCIONARIO_FAILURE = 'CREATE_FUNCIONARIO_FAILURE';

export const UPDATE_FUNCIONARIO = 'UPDATE_FUNCIONARIO';
export const INIT_UPDATE_FUNCIONARIO = 'INIT_UPDATE_FUNCIONARIO';
export const UPDATE_FUNCIONARIO_SUCCESS = 'UPDATE_FUNCIONARIO_SUCCESS';
export const UPDATE_FUNCIONARIO_FAILURE = 'UPDATE_FUNCIONARIO_FAILURE';

export const REMOVE_FUNCIONARIO = 'REMOVE_FUNCIONARIO';
export const REMOVE_FUNCIONARIO_SUCCESS = 'REMOVE_FUNCIONARIO_SUCCESS';
export const REMOVE_FUNCIONARIO_FAILURE = 'REMOVE_FUNCIONARIO_FAILURE';

export const SET_FUNCIONARIOS = 'SET_FUNCIONARIOS';
export const SET_FUNCIONARIO = 'SET_FUNCIONARIO';
export const LIST_FUNCIONARIOS = 'LIST_FUNCIONARIOS';
export const PAGINATE_FUNCIONARIOS = 'PAGINATE_FUNCIONARIOS';

export const FETCH_FUNCIONARIO = 'FETCH_FUNCIONARIO';
export const FETCH_FUNCIONARIO_FAILED = 'FETCH_FUNCIONARIO_FAILED';
export const FETCH_FUNCIONARIO_SUCCESS = 'FETCH_FUNCIONARIO_SUCCESS';
