//= ====================================
//  CRUD
//-------------------------------------

export const CREATE_JORNADA = 'CREATE_JORNADA';
export const INIT_CREATE_JORNADA = 'INIT_CREATE_JORNADA';
export const CREATE_JORNADA_SUCCESS = 'CREATE_JORNADA_SUCCESS';
export const CREATE_JORNADA_FAILURE = 'CREATE_JORNADA_FAILURE';

export const UPDATE_JORNADA = 'UPDATE_JORNADA';
export const INIT_UPDATE_JORNADA = 'INIT_UPDATE_JORNADA';
export const UPDATE_JORNADA_SUCCESS = 'UPDATE_JORNADA_SUCCESS';
export const UPDATE_JORNADA_FAILURE = 'UPDATE_JORNADA_FAILURE';

export const REMOVE_JORNADA = 'REMOVE_JORNADA';
export const REMOVE_JORNADA_SUCCESS = 'REMOVE_JORNADA_SUCCESS';
export const REMOVE_JORNADA_FAILURE = 'REMOVE_JORNADA_FAILURE';

export const SET_JORNADAS = 'SET_JORNADAS';
export const SET_JORNADA = 'SET_JORNADA';
export const LIST_JORNADAS = 'LIST_JORNADAS';

export const FETCH_JORNADA = 'FETCH_JORNADA';
export const FETCH_JORNADA_FAILED = 'FETCH_JORNADA_FAILED';
export const FETCH_JORNADA_SUCCESS = 'FETCH_JORNADA_SUCCESS';
