//= ====================================
//  CRUD
//-------------------------------------

export const CREATE_PONTO_MARCACAO = 'CREATE_PONTO_MARCACAO';
export const UPLOAD_PONTO_MARCACAO = 'UPLOAD_PONTO_MARCACAO';
export const CREATE_PONTO_MARCACAO_MODAL = 'CREATE_PONTO_MARCACAO_MODAL';
export const INIT_CREATE_PONTO_MARCACAO = 'INIT_CREATE_PONTO_MARCACAO';
export const CREATE_PONTO_MARCACAO_SUCCESS = 'CREATE_PONTO_MARCACAO_SUCCESS';
export const CREATE_PONTO_MARCACAO_FAILURE = 'CREATE_PONTO_MARCACAO_FAILURE';

export const UPDATE_PONTO_MARCACAO = 'UPDATE_PONTO_MARCACAO';
export const INIT_UPDATE_PONTO_MARCACAO = 'INIT_UPDATE_PONTO_MARCACAO';
export const UPDATE_PONTO_MARCACAO_SUCCESS = 'UPDATE_PONTO_MARCACAO_SUCCESS';
export const UPDATE_PONTO_MARCACAO_FAILURE = 'UPDATE_PONTO_MARCACAO_FAILURE';

export const REMOVE_PONTO_MARCACAO = 'REMOVE_PONTO_MARCACAO';
export const REMOVE_PONTO_MARCACAO_SUCCESS = 'REMOVE_PONTO_MARCACAO_SUCCESS';
export const REMOVE_PONTO_MARCACAO_FAILURE = 'REMOVE_PONTO_MARCACAO_FAILURE';

export const SET_PONTOS_MARCACOES = 'SET_PONTOS_MARCACOES';
export const SET_PONTO_MARCACAO = 'SET_PONTO_MARCACAO';
export const SET_PONTO_MARCACAO_SITUACOES = 'SET_PONTO_MARCACAO_SITUACOES';
export const LIST_PONTOS_MARCACOES = 'LIST_PONTOS_MARCACOES';
export const PAGINATE_PONTOS_MARCACOES = 'PAGINATE_PONTOS_MARCACOES';
export const LIST_PONTO_MARCACAO_SITUACOES = 'LIST_PONTO_MARCACAO_SITUACOES';

export const FETCH_PONTO_MARCACAO = 'FETCH_PONTO_MARCACAO';
export const FETCH_PONTO_MARCACAO_FAILED = 'FETCH_PONTO_MARCACAO_FAILED';
export const FETCH_PONTO_MARCACAO_SUCCESS = 'FETCH_PONTO_MARCACAO_SUCCESS';
