//= ====================================
//  CRUD
//-------------------------------------

export const CREATE_PROJETO = 'CREATE_PROJETO';
export const INIT_CREATE_PROJETO = 'INIT_CREATE_PROJETO';
export const CREATE_PROJETO_SUCCESS = 'CREATE_PROJETO_SUCCESS';

export const UPDATE_PROJETO = 'UPDATE_PROJETO';
export const INIT_UPDATE_PROJETO = 'INIT_UPDATE_PROJETO';
export const UPDATE_PROJETO_SUCCESS = 'UPDATE_PROJETO_SUCCESS';

export const REMOVE_PROJETO = 'REMOVE_PROJETO';
export const REMOVE_PROJETO_SUCCESS = 'REMOVE_PROJETO_SUCCESS';
export const REMOVE_PROJETO_FAILURE = 'REMOVE_PROJETO_FAILURE';

export const SET_PROJETOS = 'SET_PROJETOS';
export const SET_PROJETO = 'SET_PROJETO';
export const LIST_PROJETOS = 'LIST_PROJETOS';
export const PAGINATE_PROJETOS = 'PAGINATE_PROJETOS';

export const FETCH_PROJETO = 'FETCH_PROJETO';
export const FETCH_PROJETO_FAILED = 'FETCH_PROJETO_FAILED';
export const FETCH_PROJETO_SUCCESS = 'FETCH_PROJETO_SUCCESS';
