//= ====================================
//  CRUD
//-------------------------------------

export const CREATE_TARIFA_PRECO = 'CREATE_TARIFA_PRECO';
export const INIT_CREATE_TARIFA_PRECO = 'INIT_CREATE_TARIFA_PRECO';
export const CREATE_TARIFA_PRECO_SUCCESS = 'CREATE_TARIFA_PRECO_SUCCESS';
export const CREATE_TARIFA_PRECO_FAILURE = 'CREATE_TARIFA_PRECO_FAILURE';

export const UPDATE_TARIFA_PRECO = 'UPDATE_TARIFA_PRECO';
export const INIT_UPDATE_TARIFA_PRECO = 'INIT_UPDATE_TARIFA_PRECO';
export const UPDATE_TARIFA_PRECO_SUCCESS = 'UPDATE_TARIFA_PRECO_SUCCESS';
export const UPDATE_TARIFA_PRECO_FAILURE = 'UPDATE_TARIFA_PRECO_FAILURE';

export const REMOVE_TARIFA_PRECO = 'REMOVE_TARIFA_PRECO';
export const REMOVE_TARIFA_PRECO_SUCCESS = 'REMOVE_TARIFA_PRECO_SUCCESS';
export const REMOVE_TARIFA_PRECO_FAILURE = 'REMOVE_TARIFA_PRECO_FAILURE';

export const SET_TARIFA_PRECOS = 'SET_TARIFA_PRECOS';
export const SET_TARIFA_PRECO = 'SET_TARIFA_PRECO';
export const LIST_TARIFA_PRECOS = 'LIST_TARIFA_PRECOS';

export const FETCH_TARIFA_PRECO = 'FETCH_TARIFA_PRECO';
export const FETCH_TARIFA_PRECO_FAILED = 'FETCH_TARIFA_PRECO_FAILED';
export const FETCH_TARIFA_PRECO_SUCCESS = 'FETCH_TARIFA_PRECO_SUCCESS';
