//= ====================================
//  CRUD
//-------------------------------------

export const CREATE_TARIFA = 'CREATE_TARIFA';
export const CREATE_TARIFA_MODAL = 'CREATE_TARIFA_MODAL';
export const INIT_CREATE_TARIFA = 'INIT_CREATE_TARIFA';
export const CREATE_TARIFA_SUCCESS = 'CREATE_TARIFA_SUCCESS';
export const CREATE_TARIFA_FAILURE = 'CREATE_TARIFA_FAILURE';

export const UPDATE_TARIFA = 'UPDATE_TARIFA';
export const INIT_UPDATE_TARIFA = 'INIT_UPDATE_TARIFA';
export const UPDATE_TARIFA_SUCCESS = 'UPDATE_TARIFA_SUCCESS';
export const UPDATE_TARIFA_FAILURE = 'UPDATE_TARIFA_FAILURE';

export const REMOVE_TARIFA = 'REMOVE_TARIFA';
export const REMOVE_TARIFA_SUCCESS = 'REMOVE_TARIFA_SUCCESS';
export const REMOVE_TARIFA_FAILURE = 'REMOVE_TARIFA_FAILURE';

export const SET_TARIFAS = 'SET_TARIFAS';
export const SET_TARIFA = 'SET_TARIFA';
export const LIST_TARIFAS = 'LIST_TARIFAS';
export const PAGINATE_TARIFAS = 'PAGINATE_TARIFAS';

export const FETCH_TARIFA = 'FETCH_TARIFA';
export const FETCH_TARIFA_FAILED = 'FETCH_TARIFA_FAILED';
export const FETCH_TARIFA_SUCCESS = 'FETCH_TARIFA_SUCCESS';
