//= ====================================
//  CRUD
//-------------------------------------

export const CREATE_TIPORECURSO = 'CREATE_TIPORECURSO';
export const CREATE_TIPORECURSO_MODAL = 'CREATE_TIPORECURSO_MODAL';
export const INIT_CREATE_TIPORECURSO = 'INIT_CREATE_TIPORECURSO';
export const CREATE_TIPORECURSO_SUCCESS = 'CREATE_TIPORECURSO_SUCCESS';
export const CREATE_TIPORECURSO_FAILURE = 'CREATE_TIPORECURSO_FAILURE';

export const UPDATE_TIPORECURSO = 'UPDATE_TIPORECURSO';
export const INIT_UPDATE_TIPORECURSO = 'INIT_UPDATE_TIPORECURSO';
export const UPDATE_TIPORECURSO_SUCCESS = 'UPDATE_TIPORECURSO_SUCCESS';
export const UPDATE_TIPORECURSO_FAILURE = 'UPDATE_TIPORECURSO_FAILURE';

export const REMOVE_TIPORECURSO = 'REMOVE_TIPORECURSO';
export const REMOVE_TIPORECURSO_SUCCESS = 'REMOVE_TIPORECURSO_SUCCESS';
export const REMOVE_TIPORECURSO_FAILURE = 'REMOVE_TIPORECURSO_FAILURE';

export const SET_TIPORECURSOS = 'SET_TIPORECURSOS';
export const SET_TIPORECURSO = 'SET_TIPORECURSO';
export const LIST_TIPORECURSOS = 'LIST_TIPORECURSOS';
export const PAGINATE_TIPORECURSOS = 'PAGINATE_TIPORECURSOS';

export const FETCH_TIPORECURSO = 'FETCH_TIPORECURSO';
export const FETCH_TIPORECURSO_FAILED = 'FETCH_TIPORECURSO_FAILED';
export const FETCH_TIPORECURSO_SUCCESS = 'FETCH_TIPORECURSO_SUCCESS';
