//= ====================================
//  CRUD
//-------------------------------------

export const CREATE_TIPOATIVIDADE = 'CREATE_TIPOATIVIDADE';
export const INIT_CREATE_TIPOATIVIDADE = 'INIT_CREATE_TIPOATIVIDADE';
export const CREATE_TIPOATIVIDADE_SUCCESS = 'CREATE_TIPOATIVIDADE_SUCCESS';
export const CREATE_TIPOATIVIDADE_FAILURE = 'CREATE_TIPOATIVIDADE_FAILURE';

export const UPDATE_TIPOATIVIDADE = 'UPDATE_TIPOATIVIDADE';
export const INIT_UPDATE_TIPOATIVIDADE = 'INIT_UPDATE_TIPOATIVIDADE';
export const UPDATE_TIPOATIVIDADE_SUCCESS = 'UPDATE_TIPOATIVIDADE_SUCCESS';
export const UPDATE_TIPOATIVIDADE_FAILURE = 'UPDATE_TIPOATIVIDADE_FAILURE';

export const REMOVE_TIPOATIVIDADE = 'REMOVE_TIPOATIVIDADE';
export const REMOVE_TIPOATIVIDADE_SUCCESS = 'REMOVE_TIPOATIVIDADE_SUCCESS';
export const REMOVE_TIPOATIVIDADE_FAILURE = 'REMOVE_TIPOATIVIDADE_FAILURE';

export const SET_TIPOATIVIDADES = 'SET_TIPOATIVIDADES';
export const SET_TIPOATIVIDADE = 'SET_TIPOATIVIDADE';
export const LIST_TIPOATIVIDADES = 'LIST_TIPOATIVIDADES';
export const PAGINATE_TIPOATIVIDADES = 'PAGINATE_TIPOATIVIDADES';

export const FETCH_TIPOATIVIDADE = 'FETCH_TIPOATIVIDADE';
export const FETCH_TIPOATIVIDADE_FAILED = 'FETCH_TIPOATIVIDADE_FAILED';
export const FETCH_TIPOATIVIDADE_SUCCESS = 'FETCH_TIPOATIVIDADE_SUCCESS';
