//= ====================================
//  CRUD
//-------------------------------------

export const CREATE_TIPO_FATURAMENTO = 'CREATE_TIPO_FATURAMENTO';
export const INIT_CREATE_TIPO_FATURAMENTO = 'INIT_CREATE_TIPO_FATURAMENTO';
export const CREATE_TIPO_FATURAMENTO_SUCCESS = 'CREATE_TIPO_FATURAMENTO_SUCCESS';
export const CREATE_TIPO_FATURAMENTO_FAILURE = 'CREATE_TIPO_FATURAMENTO_FAILURE';

export const UPDATE_TIPO_FATURAMENTO = 'UPDATE_TIPO_FATURAMENTO';
export const INIT_UPDATE_TIPO_FATURAMENTO = 'INIT_UPDATE_TIPO_FATURAMENTO';
export const UPDATE_TIPO_FATURAMENTO_SUCCESS = 'UPDATE_TIPO_FATURAMENTO_SUCCESS';
export const UPDATE_TIPO_FATURAMENTO_FAILURE = 'UPDATE_TIPO_FATURAMENTO_FAILURE';

export const REMOVE_TIPO_FATURAMENTO = 'REMOVE_TIPO_FATURAMENTO';
export const REMOVE_TIPO_FATURAMENTO_SUCCESS = 'REMOVE_TIPO_FATURAMENTO_SUCCESS';
export const REMOVE_TIPO_FATURAMENTO_FAILURE = 'REMOVE_TIPO_FATURAMENTO_FAILURE';

export const SET_TIPO_FATURAMENTOS = 'SET_TIPO_FATURAMENTOS';
export const SET_TIPO_FATURAMENTO = 'SET_TIPO_FATURAMENTO';
export const LIST_TIPO_FATURAMENTOS = 'LIST_TIPO_FATURAMENTOS';

export const FETCH_TIPO_FATURAMENTO = 'FETCH_TIPO_FATURAMENTO';
export const FETCH_TIPO_FATURAMENTO_FAILED = 'FETCH_TIPO_FATURAMENTO_FAILED';
export const FETCH_TIPO_FATURAMENTO_SUCCESS = 'FETCH_TIPO_FATURAMENTO_SUCCESS';
